services:
  erp-database:
    build: ./database
    container_name: erp-database
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - azul-net

  erp-frontend:
    build: ./frontend
    container_name: erp-frontend
    ports:
      - "80:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - erp-database
    networks:
      - azul-net

networks:
  azul-net:
    driver: bridge
